[package]
name = "rust-sha256"
version = "0.1.0"
edition = "2021"

[dependencies]
cxx = "1.0"
# These are for the public-private key generation
num-bigint = { version = "0.4", features = ["rand"] }
num-traits = "0.2"
rand = "0.8"


[build-dependencies]
cxx-build = "1.0"
